# Generated by Django 2.2.6 on 2019-10-15 15:16

from django.db import migrations


def create_types(apps, schema_editor):
    AccountType = apps.get_model("trionyx_accounts", "AccountType")
    AccountType.objects.create(name='Customer')
    AccountType.objects.create(name='Partner')


def reverse_create_types(apps, schema_editor):
    AccountType = apps.get_model("trionyx_accounts", "AccountType")
    AccountType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_types, reverse_create_types)
    ]
